#!/usr/bin/env node

var program = require('commander');

var wsend = require('./wsend.js');

//wsend.checkInstall();

program
  .version('0.0.1')
  .option('-l, --login', 'Login')
  .option('-r, --register', 'Register')
  .option('-R, --refer', 'Refer')
  .option('-L, --referlink', 'Refer Link')
  .option('-p, --noprogress', 'No Progress Bar')
  .parse(process.argv);

if (program.login) {
  wsend.login();
} else if (program.register) {
  wsend.register();
} else if (program.refer) { 
  wsend.refer(process.argv[3]);
} else if (program.referlink) { 
  wsend.referLink();
} else if (program.noprogress) { 
  wsend.sendFileNoProgress(process.argv[3]);
} else {
  if (process.argv[2]) {
    wsend.sendFile(process.argv[2]);
  } else {
    
    console.error("\033[01;31m");
    console.error('error:   ');
    console.error('error:   Usage: '+process.argv[1]+' <file>');
    console.error('error:   Usage: '+process.argv[1]+' --noprogress <file>');
    console.error('error:   Usage: '+process.argv[1]+' [-l|--login] [-r|--register]');
    console.error('error:   Usage: [--refer] friend@example.com');
    console.error('error:   Usage: [--refer-link]');
    console.error('error:   or send a file, example:');
    console.error('error:   '+process.argv[1]+' file.txt');
    console.error('error:   or without progress bar, example:');
    console.error('error:   '+process.argv[1]+' -p file.txt');
    console.error('error:   ');
    console.error("\033[00m");
  }

}

